### ISSUE TITLE
No encryptionScheme value should indicate "cenc"

### ISSUE THREAD

**Issue by ddorwin** [joeyparrish/encrypted-media-encryption-scheme#10] opened 2018-11-28 01:36 UTC
The explainer currently says:
>A missing or `null` value indicates that any encryption scheme is acceptable.

This would change the meaning of existing application code in user agents that implement this new dictionary member. In order to avoid this and be consistent with the existing EME spec and [Stream Format Registry](https://www.w3.org/TR/eme-stream-registry/), the default encryption scheme for applications that do not specify the new `encryptionScheme` dictionary member needs to be what is specified in the existing stream format entry for the `contentType`.

The Stream Format [entry for "video/mp4"](https://www.w3.org/TR/eme-stream-mp4/) is explicit that such content "shall be encrypted at the sample level with AES-128 CTR encryption," which is what `"cenc"` represents.

<br>From an API perspective, it doesn't make sense for applications to be able to indicate "any encryption scheme is acceptable" when the intended use is to determine whether the user agent can support a given media stream. It's also not possible for this to be forwards compatible should another scheme emerge in the future.

**Comment by jernoble** [comment] 2018-11-28 18:14
It seems like the Stream Format entry for "video/mp4" is wrong, since "cbcs" is supported in ISO files of that MIME type.

**Comment by ddorwin** [comment] 2018-11-28 19:00
That's really a separate discussion from this issue. Even if that was the case [1], it would still make sense to reference the registry entry rather than allowing for any encryption scheme.


[1] The meaning of `"video/mp4"` when used with EME was very intentional. This was discussed in https://github.com/w3c/encrypted-media/issues/391.

**Comment by jernoble** [comment] 2018-11-28 19:03
Yes and that bug leads directly to this new spec. MIME types do not allow you to specify an encryption scheme, and thus the registry is incorrect, or at least incomplete.

**Comment by mrstux** [comment] 2018-11-29 04:18
The issue is that current and legacy user-agents don't implement this specification, and current and legacy applications also don't utilise this specification. They instead use some sort of heuristic to guess which schemes are supported by the user-agent, and then blindly use those schemes. And the user-agents in turn, that support multiple schemes, support those schemes without having to have the schemes specified when using `requestMediaKeysSystemAccess`

Thus, not specifying `encryptionScheme` or specifically setting it to `null` needs to be the existing legacy behaviour, which for all intents is a request from the application to the user-agent to "use whatever you want"

Thus

>A missing or null value indicates that any encryption scheme is acceptable

The difference is what happens when the user-agent does understand the `encryptionScheme` member of the `MediaKeySystemMediaCapability`

What does it return when the `encryptionScheme` is `undefined`, or `null`? Because if it returns 'cenc' then that implies that the returned `MediaKeySystemAccess` can only be used for 'cenc' content, when in practise, it can be used for both 'cbcs' and/or 'cenc' content with current user-agents, depending on which schemes they do actually support. And that would be a behaviour change, and a breaking change if the non-null returned encryptionScheme were enforced.

perhaps something like:

"A missing or null value indicates that any user-agent supported encryption scheme is acceptable"

Which ties in with

>If encryptionScheme from the application is null or missing, the encryptionScheme fields in the returned configuration must be null.

Which means that if the application asks for (explicity or implicitly) "any supported scheme", then the user-agent will reply with "any supported scheme"

Which is todays current user-agent behaviour, and application usage.

Future applications will be able to ask explicitly for a specific scheme, and receive explicit access to that scheme, and also will be able to detect if the user-agent has the old behaviour, and thus "any supported scheme" is allowed.

**Comment by ddorwin** [comment] 2019-02-06 01:27
@jernoble, The Stream Format Registry describes how to signal and use specific stream formats with EME [in order to](https://w3c.github.io/encrypted-media/format-registry/stream/index.html#purpose) improve interoperability and avoid divergent and incompatible implementations. It doesn't describe all possible meanings of a MIME type and is not a MIME type registry.

It is perhaps unfortunate that 1) EME chose to use MIME types and/or `"video/mp4"` for this purpose and 2) all ISO BMFF files use "video/mp4" regardless of whether they are encrypted or the protection scheme or encryption scheme used.

Note that if we were to instead follow the MIME type definition, `"video/mp4"` would also include Scheme Types ('schm') other than ISO CENC as well as 'cbc1' and 'cens' and any other encryption scheme added to future versions of ISO CENC.

<br/>The registry solution proposed in https://github.com/WICG/encrypted-media-encryption-scheme/issues/9 provides a path forward to supporting multiple encryption schemes in the registry. I think that would allow us to remove the ambiguity in the "missing or `null`" statement from the core explainer/spec and address this issue there. At the very least, this avoids the potential for such ambiguity for other content types.

**Comment by ddorwin** [comment] 2019-02-06 01:45
@mrstux wrote:
>The issue is that current and legacy user-agents don't implement the specification, and current and legacy applications also don't utilise this specification. They instead use some sort of heuristic to guess which schemes are supported by the user-agent, and then blindly use those schemes.

_Some_ user agents didn't follow the specification, and _some_ applications used heuristics (or user agent strings) to work with such user agents.

It would be exceptional to change the existing definition of the specification - and in the process break applications that did follow the specification and were working correctly on user agents that followed it - in order to accommodate such a subset. Since such applications are already aware of the incompatible user agents, it makes more sense to update those to correctly handle new versions of those user agents.

Making the change requested in the title of this issue will make newer (compliant) versions of those user agents now compatible with all other applications. In other words, applications that followed the specification will now correctly fail with a not supported error in user agents that do not support AES-128 CTR rather than failing later after playback is attempted.


<br/>Thank you for pointing out the text about the value of "the encryptionScheme fields in the returned configuration." That is also worth revisiting once a conclusion on this related issues is reached.

**Comment by jernoble** [comment] 2019-02-06 04:51
So your solution to an admittedly unfortunate decision is to double down on the ambiguity? Why not update _all_ user agents to require a encryptionScheme when the configuration is ambiguous rather than pick one particular scheme?

**Comment by joeyparrish** [comment] 2019-06-06 19:02
As detailed in the explainer, defaulting to either `cenc` or `cbcs` will fundamentally break applications that are unaware of the new field.  As much as it might be distasteful to have a default which is left undefined or to the discretion of the individual UA, there is simply no other way to avoid breaking apps on one UA or another.

I hope we can all agree that any solution which breaks existing applications is unacceptable.

If there are no further objections, I will close this issue.

**Comment by joeyparrish** [comment] 2019-09-12 19:51
No additional comments/objections since June, so I'm closing this issue with "working as intended".  The default encryption scheme, if unspecified, is left to the discretion of the UA.

**Closed as completed by joeyparrish** 2019-09-12 19:51 UTC
Labels: working as intended

**Comment by ddorwin** [comment] 2019-09-16 20:35
Is it accurate to say that the primary goals of this incubation are the following?
1. Allow new/updated applications must be able to make intelligent choices about what content to serve to which user agents.
1. Backwards compatibility: do not (further) break existing apps that are not updated to use the new API surface.

<br>For applications that are updated to use this feature, the discussion in this issue is mostly moot. [1]

For backwards compatibility, it seems the best solution would be to _not_ change the behavior of _any_ implementations when the encryption scheme is not specified. If an application didn't use heuristics before, then it will continue to be no more broken than it was, and if the heuristics worked before, they will continue to do so.

The effect is that "A missing or `null` value indicates that encryption scheme(s) supported by the user agent before the introduction of `encryptionScheme` are acceptable." This exact language wouldn't actually go in the spec, but perhaps we can agree on that as a goal and work from there.

This approach avoids both a) breaking existing applications that rely on implementations discussed above and b) introducing ambiguity that might be problematic in the future and perhaps even encourage undesirable application behavior (i.e., applications _not_ specifying `encryptionScheme` when adding support for CBCS in additional browsers).

[1] The recommendation is that all applications be updated to specify the `encryptionScheme`, right? When specing this, it might be a good idea to add a recommendation that applications “specify the encryption scheme to avoid unexpected client incompatibilities,” similar to the one for `robustness`.
